import { analyzeRecovery, muscleProfiles, volumeOf } from './recovery-engine.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, updateProfile, sendEmailVerification, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

// Firebase Web configuration is public by design. It identifies this app;
// access to every user document is enforced by the Firestore rules.
const firebaseConfig = {
  apiKey: 'AIzaSyCM_G4B97AeKt37P5ePDSdaR47gCDM',
  authDomain: 'fitmind-f9375.firebaseapp.com',
  projectId: 'fitmind-f9375',
  storageBucket: 'fitmind-f9375.firebasestorage.app',
  messagingSenderId: '104533087149',
  appId: '1:104533087149:web:222c518d2ed5ddcfa60724'
};
const firebaseApp = initializeApp(firebaseConfig);
const firebaseAuth = getAuth(firebaseApp);
const firestore = getFirestore(firebaseApp);

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const library = [
  ['Жим лежачи',['chest','triceps'],'Груди'],['Жим гантелей похилий',['chest','triceps'],'Груди'],['Кросовер',['chest'],'Груди'],
  ['Підтягування',['back','biceps'],'Спина'],['Тяга верхнього блока',['back','biceps'],'Спина'],['Горизонтальна тяга',['back','biceps'],'Спина'],
  ['Присідання',['quads','glutes'],'Ноги'],['Жим ногами',['quads','glutes'],'Ноги'],['Румунська тяга',['hamstrings','glutes'],'Ноги'],
  ['Жим гантелей сидячи',['frontDelts','triceps'],'Плечі'],['Махи в сторони',['sideDelts'],'Плечі'],
  ['Підйом штанги на біцепс',['biceps'],'Руки'],['Молотки',['biceps'],'Руки'],['Французький жим',['triceps'],'Руки'],['Планка',['core'],'Кор']
].map(x => ({name:x[0],muscles:x[1],category:x[2]}));
const extraExercises = [
 ['Віджимання від підлоги',['chest','triceps'],'Груди'],['Жим штанги вузьким хватом',['chest','triceps'],'Груди'],['Жим у тренажері',['chest','triceps'],'Груди'],['Розводка гантелей',['chest'],'Груди'],['Пуловер',['chest','back'],'Груди'],
 ['Тяга гантелі однією рукою',['back','biceps'],'Спина'],['Тяга Т-грифа',['back','biceps'],'Спина'],['Тяга прямими руками',['back'],'Спина'],['Гіперекстензія',['lowerBack','glutes'],'Спина'],['Шраги',['traps'],'Спина'],['Зворотні підтягування',['back','biceps'],'Спина'],
 ['Фронтальні присідання',['quads','glutes'],'Ноги'],['Гак-присідання',['quads'],'Ноги'],['Болгарські випади',['quads','glutes'],'Ноги'],['Випади вперед',['quads','glutes'],'Ноги'],['Розгинання ніг',['quads'],'Ноги'],['Згинання ніг лежачи',['hamstrings'],'Ноги'],['Good morning',['hamstrings','lowerBack'],'Ноги'],['Місток зі штангою',['glutes'],'Ноги'],['Підйом на литки стоячи',['calves'],'Ноги'],['Підйом на литки сидячи',['calves'],'Ноги'],
 ['Жим штанги стоячи',['frontDelts','triceps'],'Плечі'],['Арнольд жим',['frontDelts','sideDelts'],'Плечі'],['Махи перед собою',['frontDelts'],'Плечі'],['Зворотна розводка',['rearDelts'],'Плечі'],['Face pull',['rearDelts','back'],'Плечі'],
 ['Підйом гантелей на біцепс',['biceps'],'Руки'],['Згинання на лаві Скотта',['biceps'],'Руки'],['Згинання на блоці',['biceps'],'Руки'],['Віджимання вузьким хватом',['triceps'],'Руки'],['Розгинання рук над головою',['triceps'],'Руки'],['Віджимання на брусах',['triceps','chest'],'Руки'],['Зворотні віджимання',['triceps'],'Руки'],['Згинання кистей',['forearms'],'Руки'],
 ['Скручування',['core'],'Кор'],['Підйом ніг у висі',['core'],'Кор'],['Російські скручування',['core'],'Кор'],['Колесо для преса',['core'],'Кор'],['Бічна планка',['core'],'Кор'],
 ['Берпі',['fullBody'],'Кардіо'],['Стрибки на скакалці',['calves','fullBody'],'Кардіо'],['Бігова доріжка',['fullBody'],'Кардіо'],['Велотренажер',['quads','calves'],'Кардіо'],['Гребний тренажер',['back','quads'],'Кардіо'],['Еліпс',['fullBody'],'Кардіо']
].map(x => ({name:x[0],muscles:x[1],category:x[2]}));
library.push(...extraExercises);
const advancedExercises = [
 ['Сумо-присідання',['quads','glutes'],'Ноги'],['Кроки на платформу',['quads','glutes'],'Ноги'],['Випади назад',['quads','glutes'],'Ноги'],['Випади в ходьбі',['quads','glutes'],'Ноги'],['Тяга на прямих ногах',['hamstrings','glutes','lowerBack'],'Ноги'],['Відведення ноги в тренажері',['glutes'],'Ноги'],['Приведення стегна в тренажері',['quads','glutes'],'Ноги'],['Підйом носків у тренажері',['calves'],'Ноги'],
 ['Жим штанги на похилій лаві',['chest','triceps','frontDelts'],'Груди'],['Віджимання з вузькою постановкою рук',['chest','triceps'],'Груди'],['Зведення рук у тренажері',['chest'],'Груди'],
 ['Тяга нижнього блока',['back','biceps'],'Спина'],['Підтягування нейтральним хватом',['back','biceps'],'Спина'],['Тяга гантелей на похилій лаві',['back','rearDelts'],'Спина'],['Пулдаун вузьким хватом',['back','biceps'],'Спина'],
 ['Підйом EZ-штанги на біцепс',['biceps','forearms'],'Руки'],['Концентрований підйом на біцепс',['biceps'],'Руки'],['Розгинання руки з гантеллю',['triceps'],'Руки'],['Жим вузьким хватом',['triceps','chest'],'Руки'],
 ['Махи в кросовері',['sideDelts'],'Плечі'],['Тяга до підборіддя',['frontDelts','sideDelts'],'Плечі'],['Підйом гантелей у нахилі',['rearDelts'],'Плечі'],
 ['Зворотні скручування',['core'],'Кор'],['Вакуум',['core'],'Кор'],['Dead bug',['core'],'Кор']
].map(x=>({name:x[0],muscles:x[1],category:x[2]}));
library.push(...advancedExercises);
let user, data, view = 'home', activeWorkout, editingWorkoutId = null, selectedExerciseCategory = 'all', coachHistory = [], coachBusy = false, coachQuota = {limit:3,remaining:3};
const blank = name => ({profile:{name:name,weight:0,goal:'Набір сили'},workouts:[],exercises:library.map(x=>({...x})),favorites:[],coachHistory:[],coachUsage:{date:'',count:0}});
const safe = value => String(value ?? '').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function normalize(raw,name){const value=raw||blank(name);value.profile={...(value.profile||{}),name:name};value.workouts=Array.isArray(value.workouts)?value.workouts:[];const old=Array.isArray(value.exercises)?value.exercises:[];value.exercises=[...library.map(x=>({...x})),...old.filter(x=>!library.some(item=>item.name===x.name))];value.favorites=[...new Set(Array.isArray(value.favorites)?value.favorites.map(String):[])];value.coachHistory=Array.isArray(value.coachHistory)?value.coachHistory.filter(item=>item&&typeof item.text==='string').slice(-30).map(item=>({role:item.role==='model'?'model':'user',text:item.text.slice(0,2400)})):[];value.coachUsage=value.coachUsage&&typeof value.coachUsage==='object'?value.coachUsage:{date:'',count:0};return value}
const total = w => (w.exercises||[]).reduce((a,e)=>a+(e.sets||[]).reduce((b,s)=>b+volumeOf(s),0),0);
const fmt = n => Math.round(n||0).toLocaleString('uk-UA');
const day = value => new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'short'}).format(new Date(value));
function toast(message){const box=$('#toast');box.textContent=message;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),2600)}
const userDocument = uid => doc(firestore,'users',uid);
const publicUser = account => ({id:account.uid,name:account.displayName||account.email?.split('@')[0]||'Користувач',username:'',email:account.email||''});
const parseBody = options => { try{return JSON.parse(options?.body||'{}')}catch{return {}} };
const todayKey = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function quotaFromData(value){const usage=value?.coachUsage||{},count=usage.date===todayKey()?Math.max(0,Number(usage.count)||0):0;return {limit:3,remaining:Math.max(0,3-count)}}
async function loadFirebaseProfile(account){const snapshot=await getDoc(userDocument(account.uid));const record=snapshot.exists()?snapshot.data():{};user={...publicUser(account),username:record.username||''};data=normalize(record.data,user.name);coachQuota=quotaFromData(data);if(!snapshot.exists())await setDoc(userDocument(account.uid),{name:user.name,email:user.email,username:'',data,updatedAt:new Date().toISOString()});return {user,data,coach:coachQuota}}
async function api(url,options={}){const payload=parseBody(options);if(url==='/api/auth/register'){const name=String(payload.name||'').trim(),username=String(payload.username||'').trim().toLowerCase(),email=String(payload.email||'').trim(),password=String(payload.password||'');if(!name||!/^\p{L}[\p{L}\p{N}_]{2,23}$/u.test(username)||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)throw new Error('Вкажи ім’я, нікнейм (3–24 символи), коректний email і пароль від 8 символів.');const credential=await createUserWithEmailAndPassword(firebaseAuth,email,password);await updateProfile(credential.user,{displayName:name});await setDoc(userDocument(credential.user.uid),{name,email,username,data:blank(name),updatedAt:new Date().toISOString()});await sendEmailVerification(credential.user);await signOut(firebaseAuth);return {pendingVerification:true}}if(url==='/api/auth/login'){const credential=await signInWithEmailAndPassword(firebaseAuth,String(payload.email||'').trim(),String(payload.password||''));if(!credential.user.emailVerified){await sendEmailVerification(credential.user).catch(()=>{});await signOut(firebaseAuth);throw new Error('Підтвердь email за посиланням у листі, а потім увійди.')}return loadFirebaseProfile(credential.user)}if(url==='/api/auth/logout'){await signOut(firebaseAuth);return {ok:true}}if(url==='/api/me'){if(!firebaseAuth.currentUser||!firebaseAuth.currentUser.emailVerified)throw new Error('Потрібна авторизація.');return loadFirebaseProfile(firebaseAuth.currentUser)}if(url==='/api/data'){if(!firebaseAuth.currentUser)throw new Error('Потрібна авторизація.');data=normalize(payload,user?.name||firebaseAuth.currentUser.displayName||'Користувач');await setDoc(userDocument(firebaseAuth.currentUser.uid),{name:user.name,email:user.email,username:user.username||'',data,updatedAt:new Date().toISOString()},{merge:true});coachQuota=quotaFromData(data);return {ok:true}}if(url==='/api/profile'){if(!firebaseAuth.currentUser)throw new Error('Потрібна авторизація.');const username=String(payload.username||'').trim().toLowerCase();if(username&&!/^\p{L}[\p{L}\p{N}_]{2,23}$/u.test(username))throw new Error('Нікнейм: 3–24 літери, цифри або _.');user.username=username;await updateDoc(userDocument(firebaseAuth.currentUser.uid),{username,updatedAt:new Date().toISOString()});return {user}}const headers={'Content-Type':'application/json',...(options.headers||{})};if(firebaseAuth.currentUser)headers.Authorization='Bearer '+await firebaseAuth.currentUser.getIdToken();const r=await fetch(url,{...options,headers});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Помилка сервера.');return j}
function save(){return api('/api/data',{method:'PUT',body:JSON.stringify(data)}).catch(()=>toast('Не вдалося зберегти зміни.'))}
function auth(mode='login'){
  document.body.classList.add('auth-mode');$('.app-shell').hidden=false;
  const login='<p class="auth-kicker">ЗАХИЩЕНИЙ ПРОФІЛЬ</p><h1>Радий бачити<br>тебе знову.</h1><p class="auth-copy">Твої дані доступні лише після входу в акаунт.</p><form id="login-form" class="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required placeholder="name@email.com"></label><label>Пароль<input name="password" type="password" autocomplete="current-password" minlength="8" required placeholder="Твій пароль"></label><p class="auth-error" hidden></p><button class="auth-submit">Увійти в FitMind <span>→</span></button></form><p class="auth-switch">Ще немає профілю? <button data-auth="register">Створити акаунт</button></p>';
  const register='<button class="auth-back" data-auth="login">← Назад до входу</button><p class="auth-kicker">НОВИЙ ПРОФІЛЬ</p><h1>Почнімо<br>з твого ритму.</h1><p class="auth-copy">Новий акаунт починається з порожнього журналу — лише твої дані.</p><form id="register-form" class="auth-form"><label>Твоє ім’я<input name="name" autocomplete="name" maxlength="60" required placeholder="Наприклад, Андрій"></label><label>Нікнейм<input name="username" autocomplete="username" minlength="3" maxlength="24" required placeholder="Наприклад, andrii_fit"><small class="input-hint">Для друзів у майбутньому: 3–24 літери, цифри або _</small></label><label>Email<input name="email" type="email" autocomplete="email" required placeholder="name@email.com"></label><label>Пароль<input name="password" type="password" autocomplete="new-password" minlength="8" required placeholder="Мінімум 8 символів"></label><label>Повтори пароль<input name="confirm" type="password" autocomplete="new-password" minlength="8" required placeholder="Повтори пароль"></label><p class="auth-error" hidden></p><button class="auth-submit">Створити профіль <span>→</span></button></form><p class="auth-switch">Вже є акаунт? <button data-auth="login">Увійти</button></p>';
  $('#app').innerHTML='<section class="auth-screen"><div class="auth-panel"><div class="auth-logo"><i>F</i><span>FIT<span>MIND</span><small>SMART TRAINING</small></span></div>'+(mode==='login'?login:register)+'</div><aside class="auth-visual"><div class="auth-orbit"><strong>100<small>% YOUR DATA</small></strong></div><div class="auth-note"><span>✦ PRIVATE BY DEFAULT</span><b>Твій прогрес<br>належить лише тобі.</b><p>Окремі акаунти та серверна сесія.</p></div></aside></section>';
  $$('[data-auth]').forEach(b=>b.onclick=()=>auth(b.dataset.auth));
  const error=m=>{const e=$('.auth-error');e.textContent=m;e.hidden=false};
  $('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});user=r.user;data=r.data||blank(user.name);coachQuota=r.coach||coachQuota;open()}catch(x){error(x.message)}});
  $('#register-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))return error('Паролі не співпадають.');try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:f.get('name'),username:f.get('username'),email:f.get('email'),password:f.get('password')})});if(r.pendingVerification){auth('login');toast('Перевір пошту та підтвердь адресу — після цього зможеш увійти.');return}user=r.user;data=r.data||blank(user.name);coachQuota=r.coach||coachQuota;open();toast('Профіль створено. Журнал порожній і готовий до старту.')}catch(x){error(x.message)}});
}
function head(title,sub,content){const name=String(user?.name||'Користувач'),first=name.trim().charAt(0).toUpperCase()||'F';return '<header class="top"><div><p class="eyebrow">FITMIND / '+safe(data.profile.goal||'ТРЕНУВАННЯ')+'</p><h1>'+safe(title)+'</h1><p class="sub">'+safe(sub)+'</p></div><div class="actions"><button class="account-btn" id="profile-btn"><i>'+safe(first)+'</i><span>'+safe(name.split(' ')[0])+'</span></button><button class="primary" id="new-workout">+ Додати тренування</button></div></header>'+content}
function home(){
 if(!data.workouts.length)return head('Вітаю, '+user.name+' 👋','Профіль створено. Додай перше тренування — аналітика почне працювати автоматично.','<section class="hero empty-hero"><div><span class="chip">ПОЧАТОК ШЛЯХУ</span><h2>Тут з’явиться твоя аналітика</h2><p>Немає демо-даних чи чужих рекордів. Додай одну сесію з кількома вправами та сетами.</p><button class="primary" id="new-workout">+ Додати перше тренування</button></div><div class="score-orbit"><span>—<small>READY</small></span></div></section><section class="stat-grid"><article><span>Тренувань</span><b>0</b><em>Почни зі своєї першої сесії</em></article><article><span>Підходів</span><b>0</b><em>Сети кожної вправи</em></article><article><span>Загальний обсяг</span><b>0 кг</b><em>Твій особистий старт</em></article></section>');
 const r=analyzeRecovery(data.workouts), sets=data.workouts.reduce((a,w)=>a+(w.exercises||[]).reduce((b,e)=>b+(e.sets||[]).length,0),0);
 return head('Привіт, '+user.name+' 👋','Аналітика побудована лише з твоїх тренувань.','<section class="hero"><div><span class="chip">AI RECOVERY</span><p class="label">Загальна готовність</p><strong class="big-score">'+r.readiness+'%</strong><h2>'+ (r.readiness>=70?'Ти готовий до тренування':'Сьогодні краще без рекордів')+'</h2><p>Алгоритм врахував '+data.workouts.length+' твоїх тренувань, їх обсяг та відпочинок.</p><button data-view="recovery" class="link-btn">Відкрити повний аналіз →</button></div><div class="score-orbit"><span>'+r.readiness+'%<small>READY</small></span></div></section><section class="stat-grid"><article><span>Тижневий обсяг</span><b>'+fmt(r.week)+' кг</b><em>З твоїх записаних сетів</em></article><article><span>Тренувань</span><b>'+data.workouts.length+'</b><em>У твоєму журналі</em></article><article><span>Підходів</span><b>'+sets+'</b><em>Лише твої дані</em></article></section>');
}
function workouts(){
 const rows=data.workouts.map(w=>{const exerciseList=Array.isArray(w.exercises)?w.exercises:[];return '<article class="open-workout" data-workout="'+safe(w.id)+'"><div class="datebox"><b>'+new Date(w.completedAt).getDate()+'</b><span>'+day(w.completedAt)+'</span></div><div><h3>'+safe(w.name)+'</h3><p>'+exerciseList.map(e=>safe(e.name)).join(' · ')+'</p></div><span>'+Number(w.duration||0)+' хв</span><strong>'+fmt(total(w))+' кг</strong><small>'+exerciseList.reduce((a,e)=>a+(Array.isArray(e.sets)?e.sets.length:0),0)+' сетів</small><button class="delete-workout" data-delete="'+safe(w.id)+'" title="Видалити тренування" aria-label="Видалити тренування">×</button></article>'}).join('');
 return head('Тренування','Кожне тренування може містити будь-яку кількість вправ і сетів.','<section class="card table-card"><div class="card-head"><div><p class="eyebrow">ІСТОРІЯ</p><h2>Усі тренування</h2></div><button id="new-workout" class="primary">+ Додати тренування</button></div><div class="workout-list">'+(rows||'<p class="empty-copy">Ще немає тренувань. Створи перше та додай кілька вправ.</p>')+'</div></section>');
}
function details(){const w=data.workouts.find(x=>x.id===activeWorkout);if(!w){view='workouts';return workouts()}const exerciseList=Array.isArray(w.exercises)?w.exercises:[];return head(w.name,day(w.completedAt)+' · '+w.duration+' хв · '+exerciseList.length+' вправ','<button class="back-btn" data-view="workouts">← Усі тренування</button><section class="session-summary"><article><span>Загальний обсяг</span><b>'+fmt(total(w))+' кг</b></article><article><span>Вправ</span><b>'+exerciseList.length+'</b></article><article><span>Сетів</span><b>'+exerciseList.reduce((a,e)=>a+(Array.isArray(e.sets)?e.sets.length:0),0)+'</b></article></section><section class="session-exercises">'+exerciseList.map((e,i)=>'<article class="card"><div class="card-head"><div><p class="eyebrow">ВПРАВА '+(i+1)+'</p><h2>'+safe(e.name)+'</h2></div></div><div class="set-table"><div><span>Сет</span><span>Вага</span><span>Повторення</span><span>Обсяг</span></div>' +(Array.isArray(e.sets)?e.sets:[]).map((s,n)=>'<div><span>'+(n+1)+'</span><b>'+Number(s.weight||0)+' кг</b><b>'+Number(s.reps||0)+'</b><span>'+fmt(volumeOf(s))+' кг</span></div>').join('')+'</div></article>').join('')+'</section>')}
function bodyTone(score){return score>=90?'ready':score>=70?'almost':score>=50?'caution':score>=30?'rest':'tired'}
function bodyScore(r,keys){const values=keys.map(key=>r.muscles.find(m=>m.key===key)?.score).filter(Number.isFinite);return values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length):100}
function bodyPart(r,keys,label,path){const score=bodyScore(r,keys);return '<path class="body-part '+bodyTone(score)+'" d="'+path+'"><title>'+label+': '+score+'%</title></path>'}
function bodyMap(r){return '<section class="body-recovery card"><div><p class="eyebrow">КАРТА НАВАНТАЖЕННЯ</p><h2>Твоє тіло зараз</h2><p class="copy">Наведи курсор на сектор, щоб побачити відновлення групи м’язів.</p><div class="body-legend"><span class="ready">100–90%</span><span class="almost">89–70%</span><span class="caution">69–50%</span><span class="tired">менше 50%</span></div></div><svg class="body-map" viewBox="0 0 260 410" role="img" aria-label="Карта відновлення м’язів"><circle class="body-head" cx="130" cy="34" r="22"></circle>'+bodyPart(r,['traps'],'Трапеції','M96 66 L130 54 L164 66 L151 91 L109 91 Z')+bodyPart(r,['frontDelts','sideDelts'],'Плечі','M92 77 L108 76 L111 105 L91 111 L77 96 Z M168 77 L152 76 L149 105 L169 111 L183 96 Z')+bodyPart(r,['chest'],'Груди','M106 94 L128 94 L128 137 L104 130 Z M132 94 L154 94 L156 130 L132 137 Z')+bodyPart(r,['back','lowerBack'],'Спина й поперек','M108 139 L152 139 L160 193 L100 193 Z')+bodyPart(r,['biceps'],'Біцепс','M80 105 L99 112 L88 163 L68 157 Z M180 105 L161 112 L172 163 L192 157 Z')+bodyPart(r,['triceps'],'Трицепс','M64 156 L87 164 L80 208 L61 204 Z M196 156 L173 164 L180 208 L199 204 Z')+bodyPart(r,['forearms'],'Передпліччя','M61 204 L80 208 L70 250 L53 246 Z M199 204 L180 208 L190 250 L207 246 Z')+bodyPart(r,['core'],'Прес','M108 194 L152 194 L150 234 L110 234 Z')+bodyPart(r,['glutes'],'Сідниці','M102 235 L129 235 L129 262 L99 265 Z M131 235 L158 235 L161 265 L131 262 Z')+bodyPart(r,['quads'],'Квадрицепси','M101 267 L128 263 L125 333 L96 329 Z M132 263 L159 267 L164 329 L135 333 Z')+bodyPart(r,['hamstrings'],'Біцепс стегна','M96 330 L125 334 L119 360 L92 356 Z M164 330 L135 334 L141 360 L168 356 Z')+bodyPart(r,['calves'],'Литки','M92 357 L120 361 L116 396 L95 394 Z M168 357 L140 361 L144 396 L165 394 Z')+'</svg></section>'}
function recovery(){if(!data.workouts.length)return head('AI Recovery','Після першого тренування тут з’являться персональні показники.','<section class="card"><h2>Додай перше тренування</h2><p class="copy">AI Recovery розраховує стан м’язів лише за твоїми вправами, сетами, вагою і датами.</p><button class="primary" id="new-workout">+ Створити тренування</button></section>');const r=analyzeRecovery(data.workouts);return head('AI Recovery','Оцінка навантаження на кожну м’язову групу.','<section class="recovery-banner"><div><p class="eyebrow">ЗАГАЛЬНА ГОТОВНІСТЬ</p><strong>'+r.readiness+'%</strong><p>Оцінка сильніше реагує на кількість сетів, а потім відновлюється щогодини.</p></div></section>'+bodyMap(r)+'<section class="card"><div class="card-head"><div><p class="eyebrow">ДЕТАЛЬНО</p><h2>Відновлення м’язів</h2></div></div><div class="muscle-grid">'+r.muscles.map(m=>'<article class="muscle '+m.band[1]+'"><div><b>'+m.label+'</b><strong>'+m.score+'%</strong></div><span>'+m.band[0]+'</span><i><em style="width:'+m.score+'%"></em></i><small>'+(m.last?'Останнє навантаження: '+day(m.last):'Немає недавнього навантаження')+'</small></article>').join('')+'</div></section>')}
function progress(){const all=data.workouts.reduce((a,w)=>a+total(w),0);return head('Прогрес','Тільки твої реальні тренування та результати.','<section class="stat-grid"><article><span>Вага тіла</span><b>'+(data.profile.weight||'—')+(data.profile.weight?' кг':'')+'</b><em>'+(data.profile.weight?'Вказано в профілі':'Ще не вказано')+'</em></article><article><span>Піднято за весь час</span><b>'+fmt(all)+' кг</b><em>'+data.workouts.length+' тренувань</em></article><article><span>Вправ у бібліотеці</span><b>'+data.exercises.length+'</b><em>Доступні при створенні сесії</em></article></section>')}
function exercises(){return head('Вправи','Бібліотека для твоїх тренувань.','<section class="card"><div class="card-head"><div><p class="eyebrow">БІБЛІОТЕКА</p><h2>'+data.exercises.length+' вправ</h2></div></div><div class="exercise-grid">'+data.exercises.map(e=>'<article><i>◇</i><div><h3>'+e.name+'</h3><p>'+e.category+'</p></div></article>').join('')+'</div></section>')}
function calendar(){return head('Календар','Твої тренування за датами.','<section class="card"><h2>Останні сесії</h2><div class="compact-list">'+(data.workouts.map(w=>'<div data-workout="'+w.id+'"><i>◉</i><span><b>'+w.name+'</b><small>'+day(w.completedAt)+' · '+w.duration+' хв</small></span><strong>'+fmt(total(w))+' кг</strong></div>').join('')||'<p class="empty-copy">Ще немає тренувань у календарі.</p>')+'</div></section>')}
function coach(){
 const prompts=['Що тренувати сьогодні?','Склади тренування на груди','Чи варто робити ноги сьогодні?'];
 return head('AI-тренер','Запитай про тренування, відновлення або наступну вправу.','<section class="coach"><div class="coach-intro"><span>✦</span><h2>Твій персональний тренер</h2><p>Відповіді враховують твій журнал і відновлення.</p><div class="quick-prompts">'+prompts.map(x=>'<button data-prompt="'+x+'">'+x+'</button>').join('')+'</div></div><div id="chat" class="chat"><div class="ai-msg">Привіт! Запитай мене, що краще зробити сьогодні.</div></div><form id="coach-form"><input id="coach-input" required placeholder="Наприклад: що тренувати сьогодні?"><button class="primary">Надіслати</button></form></section>');
}
function coachAnswer(question){
 const q=question.toLowerCase(), count=data.workouts.length;
 if(!count)return 'Почни з легкого full body: присідання, жим лежачи, тяга верхнього блока. Виконай по 2–3 сети, не женись за вагою.';
 const r=analyzeRecovery(data.workouts);
 if(q.includes('сьогодні')||q.includes('трен'))return r.readiness>=70?'Готовність '+r.readiness+'%. Можна тренуватися: обери м’язи з найвищим відновленням у AI Recovery.':'Готовність '+r.readiness+'%. Краще легка активність, техніка або відпочинок.';
 if(q.includes('ног'))return 'Для ніг: присідання або жим ногами, румунська тяга, згинання ніг і литки. Почни з 2–3 сетів на вправу.';
 if(q.includes('груд')||q.includes('жим'))return 'Для грудей: жим лежачи, похилий жим гантелей, кросовер. Залиш 1–2 повтори в запасі.';
 return 'Зафіксуй усі вправи та сети в одному тренуванні — тоді я точніше підкажу наступний крок.';
}
function calendarReal(){
 const today=new Date(), year=today.getFullYear(), month=today.getMonth(), first=new Date(year,month,1), offset=(first.getDay()+6)%7, start=new Date(year,month,1-offset), cells=[];
 for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toDateString(), workout=data.workouts.find(w=>new Date(w.completedAt).toDateString()===key), current=d.getMonth()===month, exerciseCount=Array.isArray(workout?.exercises)?workout.exercises.length:0;cells.push('<div class="cal-day '+(current?'':'other-month ') +(workout?'trained ':'')+(key===today.toDateString()?'today':'')+'"><b>'+d.getDate()+'</b>'+(workout?'<small>'+exerciseCount+' вправ</small>':'')+'</div>')}
 const label=new Intl.DateTimeFormat('uk-UA',{month:'long',year:'numeric'}).format(today);
 return head('Календар','Зелений — є тренування. Темний — день без тренування.','<section class="card"><div class="card-head"><div><p class="eyebrow">ТВІЙ РИТМ</p><h2>'+label+'</h2></div></div><div class="calendar real-calendar"><div class="weekday-grid"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Нд</span></div><div class="days">'+cells.join('')+'</div></div></section>');
}
function workoutTitle(){return 'Тренування · '+new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long'}).format(new Date())}
function oneSetExercise(){return '<article class="exercise-editor"><div class="editor-head"><label>Вправа<select name="exercise">'+options()+'</select></label><button type="button" class="remove-exercise">Видалити</button></div><div class="sets-box">'+setRow()+'</div><button type="button" class="text-btn add-set">+ Додати сет</button></article>'}
function openWorkout(){editingWorkoutId=null;workoutModal();const field=$('#workout-form [name="name"]');field.value=workoutTitle();field.closest('label').hidden=true;$('#exercise-list').innerHTML=oneSetExerciseV2()}
function categories(){return [...new Set(data.exercises.map(x=>x.category))].sort()}
function categoryOptions(selected=''){return '<option value="">Спочатку обери групу м’язів</option>'+categories().map(x=>'<option value="'+safe(x)+'" '+(x===selected?'selected':'')+'>'+safe(x)+'</option>').join('')}
function exerciseOptions(category,selected=''){return '<option value="">Обери вправу</option>'+data.exercises.filter(x=>x.category===category).map(x=>'<option value="'+safe(x.name)+'" '+(x.name===selected?'selected':'')+'>'+safe(x.name)+'</option>').join('')}
function exerciseEditor(exercise=null){const category=exercise?.category||'',name=exercise?.name||'',sets=exercise?.sets?.length?exercise.sets:[{weight:'',reps:''}];return '<article class="exercise-editor"><div class="editor-head"><label>Група м’язів<select data-category required>'+categoryOptions(category)+'</select></label><label>Вправа<select name="exercise" '+(category?'':'disabled')+' required>'+exerciseOptions(category,name)+'</select></label><button type="button" class="remove-exercise" title="Прибрати вправу" aria-label="Прибрати вправу">×</button></div><div class="sets-box">'+sets.map(s=>'<div class="set-input-row"><input type="number" name="weight" min="0" step="0.5" required placeholder="кг" value="'+Number(s.weight||0)+'"><input type="number" name="reps" min="1" required placeholder="повтори" value="'+Number(s.reps||0)+'"><button type="button" class="remove-set" aria-label="Прибрати сет">×</button></div>').join('')+'</div><button type="button" class="text-btn add-set">+ Додати сет</button></article>'}
function oneSetExerciseV2(){return exerciseEditor()}
function detailsV2(){const html=details();return html.replace('<button class="back-btn"','<button id="edit-workout" class="secondary-btn">Редагувати</button><button class="back-btn"')}
function editWorkout(){const workout=data.workouts.find(x=>x.id===activeWorkout);if(!workout)return;editingWorkoutId=workout.id;workoutModal();const form=$('#workout-form');form.querySelector('[name="name"]').value=workout.name;form.querySelector('[name="duration"]').value=workout.duration;form.querySelector('[name="name"]').closest('label').hidden=true;$('#exercise-list').innerHTML=(Array.isArray(workout.exercises)?workout.exercises:[]).map(exercise=>exerciseEditor({...exercise,category:data.exercises.find(x=>x.name===exercise.name)?.category||''})).join('')||oneSetExerciseV2()}
function musclesFor(exercise){return (exercise.muscles||[]).map(key=>muscleProfiles[key]?.label||key).join(' · ')}
function exerciseCatalog(){const favoriteNames=new Set(data.favorites||[]), source=selectedExerciseCategory==='favorites'?data.exercises.filter(x=>favoriteNames.has(x.name)):selectedExerciseCategory==='all'?data.exercises:data.exercises.filter(x=>x.category===selectedExerciseCategory),list=[...source].sort((a,b)=>Number(favoriteNames.has(b.name))-Number(favoriteNames.has(a.name))||a.name.localeCompare(b.name,'uk'));return head('Вправи','Познач улюблені — вони будуть першими після вибору будь-якої категорії.','<section class="card"><div class="card-head"><div><p class="eyebrow">БІБЛІОТЕКА</p><h2>'+list.length+' вправ</h2></div></div><div class="category-tabs"><button data-exercise-category="all" class="'+(selectedExerciseCategory==='all'?'active':'')+'">Усі</button><button data-exercise-category="favorites" class="'+(selectedExerciseCategory==='favorites'?'active':'')+'">♥ Улюблені ('+favoriteNames.size+')</button>'+categories().map(x=>'<button data-exercise-category="'+safe(x)+'" class="'+(selectedExerciseCategory===x?'active':'')+'">'+safe(x)+'</button>').join('')+'</div><div class="exercise-grid">'+list.map(e=>'<article class="'+(favoriteNames.has(e.name)?'is-favorite':'')+'"><i>◇</i><div><h3>'+safe(e.name)+'</h3><p><b>'+safe(e.category)+'</b> · '+safe(musclesFor(e))+'</p></div><button class="favorite-btn" data-favorite="'+safe(e.name)+'" aria-pressed="'+favoriteNames.has(e.name)+'" aria-label="'+(favoriteNames.has(e.name)?'Прибрати з улюблених':'Додати в улюблені')+'">'+(favoriteNames.has(e.name)?'♥':'♡')+'</button></article>').join('')+'</div></section>')}
function coachHistoryMarkup(){if(!coachHistory.length)return '<div class="ai-msg">Привіт! Напиши питання — я допоможу скласти безпечний наступний крок.</div>';return coachHistory.map((item,index)=>'<div class="'+(item.role==='model'?'ai-msg':'user-msg')+'" data-coach-index="'+index+'">'+safe(item.text)+'</div>').join('')}
function coachV2(){const questions=['Що тренувати сьогодні?','Чи готові ноги?','Чи готові груди й трицепс?','Склади легке full body','Склади тренування на спину','Скільки сетів зробити?','Як відновитися швидше?','Чи можна тренуватися після перерви?','Що зробити перед тренуванням?','Як збільшити вагу безпечно?'],limit=Number(coachQuota.limit)||3,remaining=Math.max(0,Number(coachQuota.remaining)||0),disabled=remaining===0?' disabled':'';return head('AI-тренер','Gemini враховує твій журнал і відновлення.','<section class="coach"><div class="coach-intro"><span>✦</span><h2>Твій персональний тренер</h2><p>Запитуй про тренування, вправи, відновлення або план на сьогодні.</p><p class="coach-quota">Сьогодні залишилося <b>'+remaining+'</b> з '+limit+' AI-запитів.</p><div class="quick-prompts big-prompts">'+questions.map(x=>'<button data-prompt="'+x+'"'+disabled+'>'+x+'</button>').join('')+'</div></div><div id="chat" class="chat">'+coachHistoryMarkup()+'</div><form id="coach-form"><input id="coach-input" maxlength="500" required'+disabled+' placeholder="Наприклад: що тренувати сьогодні після жиму?"><button class="primary" type="submit"'+disabled+'>'+(remaining?'Надіслати':'Ліміт на сьогодні вичерпано')+'</button></form></section>')}
function coachAnswerV2(question){const q=question.toLowerCase(),r=data.workouts.length?analyzeRecovery(data.workouts):null;if(q.includes('спліт'))return 'Базовий спліт на три дні: день 1 — груди, плечі, трицепс; день 2 — спина, біцепс; день 3 — ноги й прес. Для кожної вправи виконай 2–3 сети по 8–12 повторів і залишай щонайменше день відпочинку перед повторним навантаженням тієї самої групи.';if(q.includes('ног'))return r?'Ноги відновлені на '+(r.muscles.find(x=>x.key==='quads')?.score||100)+'%. Якщо це менше 70%, обери верх тіла або легку прогулянку.':'Для старту зроби присідання, жим ногами та згинання ніг по 2 сети.';if(q.includes('груди'))return r?'Груди: '+(r.muscles.find(x=>x.key==='chest')?.score||100)+'%, трицепс: '+(r.muscles.find(x=>x.key==='triceps')?.score||100)+'%.':'Почни з жиму лежачи, похилого жиму й кросовера.';if(q.includes('full'))return 'Легкий full body: присідання 2×8, жим гантелей 2×10, горизонтальна тяга 2×10, планка 2×30 секунд.';if(q.includes('спину'))return 'Для спини: тяга верхнього блока, горизонтальна тяга, face pull. Виконай 2–3 сети по 8–12 повторів.';if(q.includes('сет'))return 'Для більшості вправ почни з 2–3 робочих сетів. Перші 1–2 тижні важливіші техніка і регулярність, ніж велика вага.';if(q.includes('віднов'))return 'Сон 7–9 годин, білок у кожному прийомі їжі, вода і легка ходьба допомагають відновленню. У FitMind показник зростає щогодини і повертається до 100% за профільний час м’яза.';if(q.includes('перерв'))return 'Після перерви перший тиждень працюй приблизно на 60–70% від звичної ваги та залишай 2–3 повтори в запасі.';if(q.includes('перед'))return 'Перед тренуванням: 5–10 хвилин легкої розминки, 1–2 розігрівочні сети першої вправи і перевір техніку.';if(q.includes('вагу'))return 'Підвищуй вагу тільки коли виконав усі заплановані повтори з чистою технікою. Додавай найменший доступний крок.';return r&&r.readiness>=70?'Сьогодні готовність '+r.readiness+'%. Можеш обрати м’язи з показником 70% і вище.':'Додай тренування до журналу — так поради стануть персональнішими.'}
function coachInline(target,text){String(text).split(/(\*\*[^*]+\*\*)/g).forEach(part=>{if(part.startsWith('**')&&part.endsWith('**')){const strong=document.createElement('strong');strong.textContent=part.slice(2,-2);target.append(strong)}else target.append(document.createTextNode(part))})}
function writeCoachReply(target,message){const lines=String(message||'Не вдалося сформувати відповідь.').replace(/\r/g,'').split('\n').map(line=>line.trim()).filter(Boolean);target.replaceChildren();let list=null;for(let line of lines){line=line.replace(/^#{1,4}\s*/,'');const isItem=/^(?:[-•*]|\d+[.)])\s+/.test(line);if(isItem){if(!list){list=document.createElement('ul');list.className='coach-list';target.append(list)}const item=document.createElement('li');coachInline(item,line.replace(/^(?:[-•*]|\d+[.)])\s+/,''));list.append(item);continue}list=null;const paragraph=document.createElement('p');paragraph.className='coach-paragraph';coachInline(paragraph,line);target.append(paragraph)}}
function setCoachBusy(busy){coachBusy=busy;const unavailable=busy||Number(coachQuota.remaining)<=0,input=$('#coach-input'),button=$('#coach-form button[type="submit"]');if(input)input.disabled=unavailable;if(button){button.disabled=unavailable;button.textContent=busy?'Думаю…':Number(coachQuota.remaining)>0?'Надіслати':'Ліміт на сьогодні вичерпано'}$$('[data-prompt]').forEach(prompt=>prompt.disabled=unavailable)}
async function askCoach(q){if(coachBusy||Number(coachQuota.remaining)<=0)return toast('Ліміт AI-запитів на сьогодні вичерпано.');const chat=$('#chat');if(!chat)return;const question=document.createElement('div');question.className='user-msg';question.textContent=q;const answer=document.createElement('div');answer.className='ai-msg';answer.textContent='Думаю над порадою…';chat.append(question,answer);chat.scrollTop=chat.scrollHeight;coachHistory.push({role:'user',text:q});const usage=data.coachUsage||{};data.coachUsage={date:todayKey(),count:(usage.date===todayKey()?Number(usage.count)||0:0)+1};coachQuota=quotaFromData(data);setCoachBusy(true);try{const recovery=analyzeRecovery(data.workouts);const result=await api('/api/coach',{method:'POST',body:JSON.stringify({question:q,history:coachHistory.slice(0,-1),context:{profile:data.profile,recovery,recentWorkouts:data.workouts.slice(0,8)}})});if(result.available&&result.answer){writeCoachReply(answer,result.answer)}else{const reason=result.state==='key'?'Gemini ще не підключено. Поки дам локальну пораду з урахуванням твого журналу.':result.state==='limit'?'Gemini тимчасово недоступний через ліміт запитів. Поки дам локальну пораду.':result.state==='incomplete'?'Gemini повернув незавершену відповідь, тому показую повну локальну пораду.':'Не вдалося отримати відповідь Gemini. Поки дам локальну пораду.';writeCoachReply(answer,reason+'\n\n'+coachAnswerV2(q))}}catch{writeCoachReply(answer,'Не вдалося звернутися до Gemini. Поки дам локальну пораду.\n\n'+coachAnswerV2(q))}finally{setCoachBusy(false)}coachHistory.push({role:'model',text:String(answer.innerText||answer.textContent).slice(0,2400)});coachHistory=coachHistory.slice(-30);data.coachHistory=coachHistory;await save();chat.scrollTop=chat.scrollHeight;const quota=$('.coach-quota');if(quota)quota.innerHTML='Сьогодні залишилося <b>'+Math.max(0,Number(coachQuota.remaining)||0)+'</b> з '+(Number(coachQuota.limit)||3)+' AI-запитів.'}
function render(){const screens={home,workouts,recovery,calendar:calendarReal,exercises:exerciseCatalog,coach:coachV2,detail:detailsV2};$('#app').innerHTML=(screens[view]||home)();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind()}
function open(){data=normalize(data,user?.name||'');coachHistory=data.coachHistory;coachBusy=false;document.body.classList.remove('auth-mode');$('.app-shell').hidden=false;view='home';render()}
function options(){return (data.exercises&&data.exercises.length?data.exercises:library).map(e=>'<option value="'+safe(e.name)+'">'+safe(e.name)+'</option>').join('')}
function setRow(){return '<div class="set-input-row"><input type="number" name="weight" min="0" step="0.5" required placeholder="кг"><input type="number" name="reps" min="1" required placeholder="повтори"><button type="button" class="remove-set">×</button></div>'}
function exerciseRow(){return '<article class="exercise-editor"><div class="editor-head"><label>Вправа<select name="exercise">'+options()+'</select></label><button type="button" class="remove-exercise">Видалити</button></div><div class="sets-box">'+setRow()+setRow()+setRow()+'</div><button type="button" class="text-btn add-set">+ Додати сет</button></article>'}
function workoutModal(){$('#modal').innerHTML='<form id="workout-form" class="modal-form workout-form"><button type="button" data-close class="close" aria-label="Закрити вікно">×</button><p class="eyebrow">НОВЕ ТРЕНУВАННЯ</p><h2>Одна сесія — багато вправ</h2><p class="form-hint">Додай усі вправи, які зробив за це тренування, та їхні сети.</p><div class="form-grid"><label>Назва<input name="name" required value="Нове тренування"></label><label>Тривалість, хв<input name="duration" type="number" min="1" required value="60"></label></div><div id="exercise-list">'+exerciseRow()+'</div><button type="button" id="add-exercise" class="secondary-btn">+ Додати ще одну вправу</button><button class="primary">Зберегти тренування</button></form>';$('#modal').showModal()}
function profile(){ $('#modal').innerHTML='<form id="profile-form" class="modal-form"><button type="button" data-close class="close" aria-label="Закрити вікно">×</button><p class="eyebrow">МОЇ ДАНІ</p><h2>Налаштувати профіль</h2><label>Ім’я<input value="'+safe(user.name)+'" disabled></label><label>Нікнейм для друзів<input name="username" minlength="3" maxlength="24" value="'+safe(user.username||'')+'" placeholder="andrii_fit"><small class="input-hint">Поки що це унікальне ім’я збережене для майбутньої функції друзів.</small></label><label>Вага тіла, кг<input name="weight" type="number" min="0" max="500" value="'+Number(data.profile.weight||0)+'"></label><label>Головна ціль<select name="goal"><option>Набір сили</option><option>Набір м’язів</option><option>Схуднення</option></select></label><button class="primary">Зберегти мої дані</button><button type="button" class="logout-btn" id="logout">Вийти з акаунта</button></form>';$('#modal').showModal();$('#profile-form [name="goal"]').value=data.profile.goal}
function bind(){
  $$('[data-coach-index]').forEach(node=>{const item=coachHistory[Number(node.dataset.coachIndex)];if(item?.role==='model')writeCoachReply(node,item.text)});
 $$('#new-workout').forEach(button=>button.addEventListener('click',openWorkout));
 $$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 $$('[data-workout]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-delete]'))return;activeWorkout=x.dataset.workout;view='detail';render()});
 $$('[data-delete]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!confirm('Видалити це тренування?'))return;data.workouts=data.workouts.filter(w=>w.id!==b.dataset.delete);await save();render();toast('Тренування видалено.')});
 $('#profile-btn')?.addEventListener('click',profile);
 $('#modal').onclick=e=>{if(e.target.closest('[data-close]'))$('#modal').close();if(e.target.closest('#add-exercise'))$('#exercise-list').insertAdjacentHTML('beforeend',exerciseRow());if(e.target.closest('.add-set'))e.target.closest('.exercise-editor').querySelector('.sets-box').insertAdjacentHTML('beforeend',setRow());if(e.target.closest('.remove-set')&&e.target.closest('.sets-box').children.length>1)e.target.closest('.set-input-row').remove();if(e.target.closest('.remove-exercise')&&$$('.exercise-editor').length>1)e.target.closest('.exercise-editor').remove();if(e.target.closest('#logout'))api('/api/auth/logout',{method:'POST',body:'{}'}).finally(()=>{user=null;data=blank('');$('#modal').close();auth()})};
  $('#modal').onsubmit=async e=>{if(e.target.id==='profile-form'){e.preventDefault();const f=new FormData(e.target),username=String(f.get('username')||'').trim();try{const result=await api('/api/profile',{method:'PUT',body:JSON.stringify({username})});user=result.user;data.profile.weight=Number(f.get('weight'))||0;data.profile.goal=f.get('goal');await save();$('#modal').close();render();toast('Дані профілю збережено.')}catch(error){toast(error.message)}return}if(e.target.id==='workout-form'){e.preventDefault();const f=new FormData(e.target), exercises=$$('.exercise-editor').map(card=>{const name=card.querySelector('[name="exercise"]').value,base=data.exercises.find(x=>x.name===name);return {name:name,muscles:base.muscles,sets:[...card.querySelectorAll('.set-input-row')].map(row=>({weight:Number(row.querySelector('[name="weight"]').value),reps:Number(row.querySelector('[name="reps"]').value)})).filter(s=>s.reps>0)}}).filter(x=>x.sets.length);if(!exercises.length)return toast('Додай хоча б один коректний сет.');data.workouts.unshift({id:crypto.randomUUID(),name:f.get('name'),duration:Number(f.get('duration')),completedAt:new Date().toISOString(),exercises:exercises});await save();$('#modal').close();view='workouts';render();toast('Тренування збережено — аналітика оновлена.')}};
 /*
 $('#new-workout')?.addEventListener('click',workoutModal);$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$$('[data-workout]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-delete]'))return;activeWorkout=x.dataset.workout;view='detail';render()});$$('[data-delete]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!confirm('Видалити це тренування?'))return;data.workouts=data.workouts.filter(w=>w.id!==b.dataset.delete);await save();render()});$('#profile-btn')?.addEventListener('click',profile);$('[data-close]')?.addEventListener('click',()=>$('#modal').close());$('#logout')?.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});$('#modal').close();auth()});
 $('#add-exercise')?.addEventListener('click',()=>$('#exercise-list').insertAdjacentHTML('beforeend',exerciseRow()));$('#exercise-list')?.addEventListener('click',e=>{if(e.target.closest('.add-set'))e.target.closest('.exercise-editor').querySelector('.sets-box').insertAdjacentHTML('beforeend',setRow());if(e.target.closest('.remove-set')&&e.target.closest('.sets-box').children.length>1)e.target.closest('.set-input-row').remove();if(e.target.closest('.remove-exercise')&&$$('.exercise-editor').length>1)e.target.closest('.exercise-editor').remove()});
 $('#workout-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target), exercises=$$('.exercise-editor').map(card=>{const name=card.querySelector('[name="exercise"]').value,base=data.exercises.find(x=>x.name===name);return {name,muscles:base.muscles,sets:[...card.querySelectorAll('.set-input-row')].map(row=>({weight:Number(row.querySelector('[name="weight"]').value),reps:Number(row.querySelector('[name="reps"]').value})).filter(s=>s.reps>0)}}).filter(x=>x.sets.length);if(!exercises.length)return toast('Додай хоча б один коректний сет.');data.workouts.unshift({id:crypto.randomUUID(),name:f.get('name'),duration:Number(f.get('duration')),completedAt:new Date().toISOString(),exercises});await save();$('#modal').close();view='workouts';render();toast('Тренування збережено — аналітика оновлена.')});
 $('#profile-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);data.profile.weight=Number(f.get('weight'))||0;data.profile.goal=f.get('goal');await save();$('#modal').close();render();toast('Дані профілю збережено.')});
}
 */ }
document.addEventListener('click',async e=>{
 const add=e.target.closest('#add-exercise');
 if(add){e.preventDefault();e.stopImmediatePropagation();$('#exercise-list').insertAdjacentHTML('beforeend',oneSetExerciseV2());return}
 const remove=e.target.closest('[data-delete]');
  if(remove){e.preventDefault();e.stopImmediatePropagation();if(!confirm('Видалити це тренування?'))return;data.workouts=data.workouts.filter(w=>w.id!==remove.dataset.delete);await save();render();toast('Тренування видалено.');return}
  const favorite=e.target.closest('[data-favorite]');
  if(favorite){e.preventDefault();e.stopImmediatePropagation();const name=favorite.dataset.favorite,items=new Set(data.favorites||[]),wasFavorite=items.has(name);wasFavorite?items.delete(name):items.add(name);data.favorites=[...items];await save();render();toast(wasFavorite?'Прибрано з улюблених.':'Додано в улюблені.');return}
 const prompt=e.target.closest('[data-prompt]');
 if(prompt){await askCoach(prompt.dataset.prompt)}
},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='coach-form')return;e.preventDefault();const input=$('#coach-input'),q=input.value.trim();if(!q)return;input.value='';await askCoach(q)});
document.addEventListener('click',e=>{const category=e.target.closest('[data-exercise-category]');if(category){selectedExerciseCategory=category.dataset.exerciseCategory;view='exercises';render();return}if(e.target.closest('#edit-workout')){e.preventDefault();editWorkout()}},true);
document.addEventListener('change',e=>{if(!e.target.matches('[data-category]'))return;const card=e.target.closest('.exercise-editor'),select=card.querySelector('[name="exercise"]'),category=e.target.value;select.disabled=!category;select.innerHTML=exerciseOptions(category);});
document.addEventListener('submit',async e=>{
 if(e.target.id!=='workout-form')return;
 e.preventDefault();e.stopImmediatePropagation();
 const form=new FormData(e.target), exercises=$$('.exercise-editor').map(card=>{const name=card.querySelector('[name="exercise"]').value,base=data.exercises.find(x=>x.name===name);if(!base)return null;return {name:name,muscles:base.muscles,sets:[...card.querySelectorAll('.set-input-row')].map(row=>({weight:Number(row.querySelector('[name="weight"]').value),reps:Number(row.querySelector('[name="reps"]').value)})).filter(s=>s.reps>0)}}).filter(x=>x&&x.sets.length);
 if(!exercises.length)return toast('Обери вправу та заповни хоча б один сет.');
  if(editingWorkoutId){const workout=data.workouts.find(x=>x.id===editingWorkoutId);if(workout){workout.duration=Math.max(1,Number(form.get('duration'))||60);workout.exercises=exercises;}editingWorkoutId=null;toast('Тренування змінено. Аналітика оновлена.')}else{data.workouts.unshift({id:crypto.randomUUID(),name:String(form.get('name')||workoutTitle()).trim().slice(0,80)||workoutTitle(),duration:Math.max(1,Number(form.get('duration'))||60),completedAt:new Date().toISOString(),exercises:exercises});toast('Тренування збережено — аналітика оновлена.')}
 await save();$('#modal').close();view='workouts';render();
},true);
function boot(){document.body.classList.add('auth-mode');onAuthStateChanged(firebaseAuth,async account=>{if(!account||!account.emailVerified){auth();return}try{const r=await loadFirebaseProfile(account);user=r.user;data=r.data||blank(user.name);coachQuota=r.coach||coachQuota;open()}catch{auth()}})}
boot();
